---
abstract: 'A simple Linked Data implementation'
author:
  - 'Kjetil Kjernsmo, C<< <kjetilk@cpan.org> >>'
  - 'Kjetil Kjernsmo <kjetilk@cpan.org>'
build_requires:
  Config::JFDI: 0
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  Test::Exception: 0
  Test::JSON: 0
  Test::More: 0.88
  Test::RDF: 0.26
  Test::WWW::Mechanize::PSGI: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-LinkedData
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Config::JFDI: 0
  JSON: 0
  Plack::Middleware::CrossOrigin: 0
  RDF::Endpoint: 0.03
  RDF::Generator::Void: 0.04
requires:
  Encode: 0
  HTML::HTML5::Writer: 0
  HTTP::Headers: 0
  Log::Log4perl: 0
  Module::Load::Conditional: 0
  Moose: 0
  MooseX::Log::Log4perl::Easy: 0
  MooseX::UndefTolerant: 0
  Plack: 0.9939
  RDF::Helper::Properties: 0.1
  RDF::RDFa::Generator: 0.102
  RDF::Trine: 0.133
  Scalar::Util: 0
  URI: 1.52
  namespace::autoclean: 0.12
resources:
  bugtracker: https://github.com/kjetilk/RDF-LinkedData/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kjetilk/RDF-LinkedData.git
version: 0.55_2
