---
abstract: 'A Linked Data server implementation'
author:
  - 'This module was started by by Gregory Todd Williams C<<'
  - 'Kjetil Kjernsmo <kjetilk@cpan.org>'
build_requires:
  Config::JFDI: 0
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  Test::Exception: 0
  Test::JSON: 0
  Test::More: 0.88
  Test::RDF: 0.2
  Test::WWW::Mechanize::PSGI: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-LinkedData
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Config::JFDI: 0
  JSON: 0
  RDF::Endpoint: 0
requires:
  HTTP::Headers: 0
  Log::Log4perl: 0
  Moose: 0
  MooseX::Log::Log4perl::Easy: 0
  Plack: 0.9939
  RDF::Helper::Properties: 0.1
  RDF::Trine: 0.133
  Scalar::Util: 0
  URI: 1.52
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=RDF-LinkedData
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kjetilk/RDF-LinkedData.git
version: 0.21_2
