---
abstract: 'Base class and scripts for servers that serve RDF as Linked Data.'
author:
  - 'Kjetil Kjernsmo <kjetilk@cpan.org>'
build_requires:
  Config::JFDI: '0'
  FindBin: '0'
  RDF::RDFa::Parser: '0'
  Test::Exception: '0'
  Test::JSON: '0'
  Test::More: '0.88'
  Test::RDF: '1.16'
  Test::WWW::Mechanize::PSGI: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.023, CPAN::Meta::Converter version 2.142060'
keywords:
  - 'Semantic Web'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: RDF-LinkedData
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Plack::App::RDF::LinkedData:
    file: lib/Plack/App/RDF/LinkedData.pm
  RDF::LinkedData:
    file: lib/RDF/LinkedData.pm
    version: '0.70'
recommends:
  Config::JFDI: '0'
  JSON: '0'
  Plack::Middleware::CrossOrigin: '0'
  Plack::Middleware::Expires: '0'
  RDF::Endpoint: '0.05'
  RDF::Generator::Void: '0.04'
requires:
  Digest::MD5: '0'
  Encode: '0'
  HTML::HTML5::Writer: '0'
  HTTP::Headers: '0'
  List::Util: '1.33'
  Log::Contextual: '0'
  Log::Log4perl: '0'
  Module::Load::Conditional: '0'
  Moo: '0'
  Plack: '0.9939'
  RDF::Helper::Properties: '0.10'
  RDF::RDFa::Generator: '0.102'
  RDF::Trine: '0.133'
  Scalar::Util: '0'
  Try::Tiny: '0'
  Types::Standard: '0'
  URI: '1.52'
  URI::NamespaceMap: '0'
  namespace::autoclean: '0.12'
resources:
  IRC: irc://irc.perl.org/#perlrdf
  Identifier: http://purl.org/NET/cpan-uri/dist/RDF-LinkedData/project
  Mailinglist: http://lists.perlrdf.org/listinfo/dev
  Wiki: http://wiki.perlrdf.org/
  bugtracker: https://github.com/kjetilk/RDF-LinkedData/issues
  homepage: https://metacpan.org/release/RDF-LinkedData
  license: http://dev.perl.org/licenses/
  repository: https://github.com/kjetilk/RDF-LinkedData/
version: '0.70'
x_contributors:
  - 'Gregory Todd Williams <gwilliams@cpan.org>'
x_provides_scripts:
  linked_data.psgi:
    file: script/linked_data.psgi
